### ISSUE TITLE
panic: EOF

### ISSUE THREAD

**Issue by vmpartner** [rwcarlsen/goexif#56]
Get error panic: EOF from decode

**Comment by mpl** [comment]
Hello.

There is not much we can do from this bug report.

Could you please provide more information, such as:

-what method/function the caller was using
-what the input file was

**Comment by ajthemacboy** [comment]
I'm getting this too. [Here is one of the photos that causes the error](https://drive.google.com/file/d/147wEv7okt9obJjqPw6n7p_L6wo7zJsGL/view?usp=sharing) on Google Drive (there are others too, but some taken on the same camera work).

Here is my relevant code:
```
f, err := os.Open(path); if err != nil { panic(err) }
x, err := exif.Decode(f); if err != nil { panic(err) }
```

Here is the error:
```
panic: EOF

goroutine 1 [running]:
main.main.func1(0xc042054180, 0x5d, 0x5415c0, 0xc0420c4000, 0x0, 0x0, 0x0, 0x0)
	D:/dev/golang/2018-05/exifsort/exifsort.go:31 +0x300
path/filepath.walk(0xc042054180, 0x5d, 0x5415c0, 0xc0420c4000, 0x532128, 0x0, 0x0)
	D:/bin/goroot/src/path/filepath/path.go:357 +0x409
path/filepath.walk(0x52f342, 0x24, 0x5415c0, 0xc0420c4000, 0x532128, 0x0, 0xc042081f78)
	D:/bin/goroot/src/path/filepath/path.go:381 +0x2c9
path/filepath.Walk(0x52f342, 0x24, 0x532128, 0xc042081f78, 0xc042054058)
	D:/bin/goroot/src/path/filepath/path.go:403 +0x10d
main.main()
	D:/dev/golang/2018-05/exifsort/exifsort.go:16 +0x49
```

I am able to read the EXIF with the 'ExifRead' package for Python, and File Explorer on Windows shows EXIF info.

**Comment by harshit777** [comment]
panic: EOF

goroutine 1 [running]:
main.main()
        /home/harshit/Projects/twitter-golang/main.go:50 +0x810
exit status 2


Getting this error

**Comment by tpiros** [comment]
I have the same issue - not sure if this is still being tracked here though ...

**Comment by taomin597715379** [comment]
I have the same issue -  not sure if this is still being tracked here though ...

**Comment by TheBellman** [comment]
see #78  - this may be a common problem
